name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        ANSIBLE_HOST: ${{ secrets.ANSIBLE_HOST }}
        ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
        ANSIBLE_HOST: ${{ secrets.ANSIBLE_HOST }}
        ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
